theme: jekyll-theme-minimal
title: Bach Violin Dataset
description: A collection of high-quality public recordings of Bach's sonatas and partitas for solo violin (BWV 1001–1006)
icons:
  homepage: fa-solid fa-globe-asia
  video: fa-brands fa-youtube
  paper: fa-solid fa-file-pdf
  slides: fa-solid fa-file-pdf
  poster: fa-solid fa-file-pdf
  arxiv: fa-solid fa-archive
  code: fa-brands fa-github
  documentation: fa-solid fa-book
  reviews: fa-solid fa-comments
